services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -"8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev:db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
